/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lolExchangeSol from "./LOLExchange.sol";
export type { lolExchangeSol };
export type { LOL } from "./LOL";
export type { LOLToken } from "./LOLToken";
