/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LOL } from "./LOL";
export type { LOLExchange } from "./LOLExchange";
export type { LOLNFTExchange } from "./LOLNFTExchange";
export type { LOLToken } from "./LOLToken";
