/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as lolExchangeSol from "./LOLExchange.sol";
export { LOL__factory } from "./LOL__factory";
export { LOLToken__factory } from "./LOLToken__factory";
